const admin = require("firebase-admin");

const serviceAccount = require("./serviceAccountKey.json");

admin.initializeApp({
  credential: admin.credential.cert(serviceAccount),
});

const db = admin.firestore();

const doctors = [
  {
    staffId: "DOC1001",
    name: "Dr. Ahmed Kamal",
    nameAr: "د. أحمد كمال",
    email: "queueless.staff+test1001@gmail.com",
    password: "Doctor123",
    department: "Emergency Medicine",
    departmentAr: "طب الطوارئ",
    specialty: "Consultant Emergency Medicine",
    specialtyAr: "استشاري طب الطوارئ",
    languages: ["English", "Arabic"],
    hospital: "NMC Royal Hospital Khalifa City, Abu Dhabi",
    hospitalAr: "مستشفى إن إم سي رويال خليفة سيتي، أبوظبي",
    role: "doctor",
  },
  {
    staffId: "DOC1002",
    name: "Dr. Ali Nawaz",
    nameAr: "د. علي نواز",
    email: "queueless.staff+test1002@gmail.com",
    password: "Doctor123",
    department: "Emergency Medicine",
    departmentAr: "طب الطوارئ",
    specialty: "Chair of Emergency Medicine",
    specialtyAr: "رئيس قسم طب الطوارئ",
    languages: ["English", "Hindi", "Urdu", "Punjabi"],
    hospital: "NMC Royal Hospital Khalifa City, Abu Dhabi",
    hospitalAr: "مستشفى إن إم سي رويال خليفة سيتي، أبوظبي",
    role: "doctor",
  },
  {
    staffId: "DOC1003",
    name: "Dr. Abdul Mujeer",
    nameAr: "د. عبد المجير",
    email: "queueless.staff+test1003@gmail.com",
    password: "Doctor123",
    department: "Cardiology",
    departmentAr: "أمراض القلب",
    specialty: "Interventional Cardiologist",
    specialtyAr: "استشاري قلب تداخلي",
    languages: ["English", "Hindi", "Urdu"],
    hospital: "NMC Specialty Hospital, Al Ain",
    hospitalAr: "مستشفى إن إم سي التخصصي، العين",
    role: "doctor",
  },
  {
    staffId: "DOC1004",
    name: "Dr. Ahmed Mohammed Al Kamali",
    nameAr: "د. أحمد محمد الكمالي",
    email: "queueless.staff+test1004@gmail.com",
    password: "Doctor123",
    department: "Cardiology",
    departmentAr: "أمراض القلب",
    specialty: "Paediatric Cardiologist",
    specialtyAr: "استشاري قلب أطفال",
    languages: ["English", "Arabic"],
    hospital: "NMC Royal Hospital Sharjah",
    hospitalAr: "مستشفى إن إم سي رويال، الشارقة",
    role: "doctor",
  },
  {
    staffId: "DOC1005",
    name: "Dr. Adam Abedalhadi Altiti",
    nameAr: "د. آدم عبد الهادي التيتي",
    email: "queueless.staff+test1005@gmail.com",
    password: "Doctor123",
    department: "Dermatology",
    departmentAr: "الأمراض الجلدية",
    specialty: "Specialist Dermatology",
    specialtyAr: "أخصائي الأمراض الجلدية",
    languages: ["English", "Arabic"],
    hospital: "NMC Royal Hospital Khalifa City, Abu Dhabi",
    hospitalAr: "مستشفى إن إم سي رويال خليفة سيتي، أبوظبي",
    role: "doctor",
  },
  {
    staffId: "DOC1006",
    name: "Dr. Ahmed Mohsen Ahmed Ameen",
    nameAr: "د. أحمد محسن أحمد أمين",
    email: "queueless.staff+test1006@gmail.com",
    password: "Doctor123",
    department: "Dermatology",
    departmentAr: "الأمراض الجلدية",
    specialty: "Consultant Dermatology",
    specialtyAr: "استشاري الأمراض الجلدية",
    languages: ["English", "Arabic"],
    hospital: "NMC Specialty Hospital, Abu Dhabi",
    hospitalAr: "مستشفى إن إم سي التخصصي، أبوظبي",
    role: "doctor",
  },
  {
    staffId: "DOC1007",
    name: "Dr. Abdul Razzak Juratli",
    nameAr: "د. عبد الرزاق جوراتلي",
    email: "queueless.staff+test1007@gmail.com",
    password: "Doctor123",
    department: "ENT",
    departmentAr: "الأنف والأذن والحنجرة",
    specialty: "Consultant ENT",
    specialtyAr: "استشاري الأنف والأذن والحنجرة",
    languages: ["English", "Arabic"],
    hospital: "NMC Royal Hospital Sharjah",
    hospitalAr: "مستشفى إن إم سي رويال، الشارقة",
    role: "doctor",
  },
  {
    staffId: "DOC1008",
    name: "Dr. Ahmed Abdelatty Elsayed",
    nameAr: "د. أحمد عبد العاطي السيد",
    email: "queueless.staff+test1008@gmail.com",
    password: "Doctor123",
    department: "ENT",
    departmentAr: "الأنف والأذن والحنجرة",
    specialty: "Consultant ENT",
    specialtyAr: "استشاري الأنف والأذن والحنجرة",
    languages: ["English", "Arabic"],
    hospital: "NMC Royal Hospital Khalifa City, Abu Dhabi",
    hospitalAr: "مستشفى إن إم سي رويال خليفة سيتي، أبوظبي",
    role: "doctor",
  },
  {
    staffId: "DOC1009",
    name: "Dr. Abdul Rasheed Koppath",
    nameAr: "د. عبد الرشيد كوباث",
    email: "queueless.staff+test1009@gmail.com",
    password: "Doctor123",
    department: "Internal Medicine",
    departmentAr: "الطب الباطني",
    specialty: "Specialist Internal Medicine",
    specialtyAr: "أخصائي الطب الباطني",
    languages: ["English", "Hindi", "Malayalam"],
    hospital: "NMC Medical Centre, Sharqan, Sharjah",
    hospitalAr: "مركز إن إم سي الطبي، الشرقان، الشارقة",
    role: "doctor",
  },
  {
    staffId: "DOC1010",
    name: "Dr. Ahmed Abdelrahman",
    nameAr: "د. أحمد عبد الرحمن",
    email: "queueless.staff+test1010@gmail.com",
    password: "Doctor123",
    department: "Internal Medicine",
    departmentAr: "الطب الباطني",
    specialty: "Consultant Internal Medicine",
    specialtyAr: "استشاري الطب الباطني",
    languages: ["English", "Arabic"],
    hospital: "NMC Royal Hospital Khalifa City, Abu Dhabi",
    hospitalAr: "مستشفى إن إم سي رويال خليفة سيتي، أبوظبي",
    role: "doctor",
  },
  {
    staffId: "DOC1011",
    name: "Dr. Abhilasha Maheshwari",
    nameAr: "د. أبهيلاشا ماهيشواري",
    email: "queueless.staff+test1011@gmail.com",
    password: "Doctor123",
    department: "Ophthalmology",
    departmentAr: "طب العيون",
    specialty: "Specialist Ophthalmologist",
    specialtyAr: "أخصائي طب العيون",
    languages: ["English", "Hindi"],
    hospital: "NMC Specialty Hospital, Abu Dhabi",
    hospitalAr: "مستشفى إن إم سي التخصصي، أبوظبي",
    role: "doctor",
  },
  {
    staffId: "DOC1012",
    name: "Dr. Adel Mohamed Alraisi",
    nameAr: "د. عادل محمد الرئيسي",
    email: "queueless.staff+test1012@gmail.com",
    password: "Doctor123",
    department: "Ophthalmology",
    departmentAr: "طب العيون",
    specialty: "Consultant Ophthalmology",
    specialtyAr: "استشاري طب العيون",
    languages: ["English", "Arabic"],
    hospital: "NMC Royal Hospital Khalifa City, Abu Dhabi",
    hospitalAr: "مستشفى إن إم سي رويال خليفة سيتي، أبوظبي",
    role: "doctor",
  },
  {
    staffId: "DOC1013",
    name: "Dr. Abtan Ahmad Al-Talafih",
    nameAr: "د. أبتان أحمد التلافحة",
    email: "queueless.staff+test1013@gmail.com",
    password: "Doctor123",
    department: "Gastroenterology",
    departmentAr: "أمراض الجهاز الهضمي",
    specialty: "Consultant Gastroenterology",
    specialtyAr: "استشاري أمراض الجهاز الهضمي",
    languages: ["English", "Arabic"],
    hospital: "NMC Royal Hospital Sharjah",
    hospitalAr: "مستشفى إن إم سي رويال، الشارقة",
    role: "doctor",
  },
  {
    staffId: "DOC1014",
    name: "Dr. Anand Vadivel",
    nameAr: "د. أناند فاديفيل",
    email: "queueless.staff+test1014@gmail.com",
    password: "Doctor123",
    department: "Gastroenterology",
    departmentAr: "أمراض الجهاز الهضمي",
    specialty: "Specialist Gastroenterology",
    specialtyAr: "أخصائي أمراض الجهاز الهضمي",
    languages: ["English", "Hindi"],
    hospital: "NMC Royal Hospital Khalifa City, Abu Dhabi",
    hospitalAr: "مستشفى إن إم سي رويال خليفة سيتي، أبوظبي",
    role: "doctor",
  },
  {
    staffId: "DOC1015",
    name: "Dr. Ahmed Ebied",
    nameAr: "د. أحمد عبيد",
    email: "queueless.staff+test1015@gmail.com",
    password: "Doctor123",
    department: "Neuroscience",
    departmentAr: "علوم الأعصاب",
    specialty: "Consultant Neurologist",
    specialtyAr: "استشاري أعصاب",
    languages: ["English", "Arabic"],
    hospital: "NMC Royal Hospital Sharjah",
    hospitalAr: "مستشفى إن إم سي رويال، الشارقة",
    role: "doctor",
  },
  {
    staffId: "DOC1016",
    name: "Dr. Aju Abraham John",
    nameAr: "د. أجو أبراهام جون",
    email: "queueless.staff+test1016@gmail.com",
    password: "Doctor123",
    department: "Neuroscience",
    departmentAr: "علوم الأعصاب",
    specialty: "Specialist Neurologist",
    specialtyAr: "أخصائي أعصاب",
    languages: ["English", "Hindi"],
    hospital: "NMC Specialty Hospital, Al Ain",
    hospitalAr: "مستشفى إن إم سي التخصصي، العين",
    role: "doctor",
  },
  {
    staffId: "DOC1017",
    name: "Dr. Abdel Razaq Ahmad Alyasin",
    nameAr: "د. عبد الرزاق أحمد الياسين",
    email: "queueless.staff+test1017@gmail.com",
    password: "Doctor123",
    department: "Paediatrics",
    departmentAr: "طب الأطفال",
    specialty: "Pediatric Endocrinology",
    specialtyAr: "غدد صماء الأطفال",
    languages: ["English", "Arabic"],
    hospital: "NMC",
    hospitalAr: "إن إم سي",
    role: "doctor",
  },
  {
    staffId: "DOC1018",
    name: "Dr. Abdelhameed Mostafa Elmesery",
    nameAr: "د. عبد الحميد مصطفى المسيري",
    email: "queueless.staff+test1018@gmail.com",
    password: "Doctor123",
    department: "Paediatrics",
    departmentAr: "طب الأطفال",
    specialty: "Head of Paediatrics",
    specialtyAr: "رئيس قسم طب الأطفال",
    languages: ["English", "Arabic"],
    hospital: "NMC Royal Hospital Khalifa City, Abu Dhabi",
    hospitalAr: "مستشفى إن إم سي رويال خليفة سيتي، أبوظبي",
    role: "doctor",
  },
  {
    staffId: "DOC1019",
    name: "Dr. Ahmed ElMansoury",
    nameAr: "د. أحمد المنصوري",
    email: "queueless.staff+test1019@gmail.com",
    password: "Doctor123",
    department: "Pulmonology",
    departmentAr: "أمراض الرئة",
    specialty: "Consultant Pulmonologist",
    specialtyAr: "استشاري أمراض الرئة",
    languages: ["English", "Arabic"],
    hospital: "NMC Royal Hospital Sharjah",
    hospitalAr: "مستشفى إن إم سي رويال، الشارقة",
    role: "doctor",
  },
  {
    staffId: "DOC1020",
    name: "Dr. Ali Anwar Mohammad",
    nameAr: "د. علي أنور محمد",
    email: "queueless.staff+test1020@gmail.com",
    password: "Doctor123",
    department: "Pulmonology",
    departmentAr: "أمراض الرئة",
    specialty: "Specialist Pulmonologist",
    specialtyAr: "أخصائي أمراض الرئة",
    languages: ["English", "Hindi"],
    hospital: "NMC Specialty Hospital, Al Ain",
    hospitalAr: "مستشفى إن إم سي التخصصي، العين",
    role: "doctor",
  },
  {
    staffId: "DOC1021",
    name: "Dr. Aarti Desai",
    nameAr: "د. آرتي ديساي",
    email: "queueless.staff+test1021@gmail.com",
    password: "Doctor123",
    department: "Dentistry",
    departmentAr: "طب الأسنان",
    specialty: "General Dentist",
    specialtyAr: "طبيب أسنان عام",
    languages: ["English", "Hindi"],
    hospital: "NMC Royal Hospital DIP, Dubai",
    hospitalAr: "مستشفى إن إم سي رويال دي آي بي، دبي",
    role: "doctor",
  },
  {
    staffId: "DOC1022",
    name: "Dr. Abraham Vinod Korath",
    nameAr: "د. أبراهام فينود كوراث",
    email: "queueless.staff+test1022@gmail.com",
    password: "Doctor123",
    department: "Dentistry",
    departmentAr: "طب الأسنان",
    specialty: "Orthodontist",
    specialtyAr: "أخصائي تقويم الأسنان",
    languages: ["English", "Hindi"],
    hospital: "NMC Royal Medical Centre, RAK",
    hospitalAr: "مركز إن إم سي رويال الطبي، رأس الخيمة",
    role: "doctor",
  },
  {
    staffId: "DOC1023",
    name: "Dr. Aamir Cheema",
    nameAr: "د. عامر شيما",
    email: "queueless.staff+test1023@gmail.com",
    password: "Doctor123",
    department: "Family Medicine",
    departmentAr: "طب الأسرة",
    specialty: "Consultant Family Medicine",
    specialtyAr: "استشاري طب الأسرة",
    languages: ["English", "Hindi"],
    hospital: "NMC Royal Hospital DIP, Dubai",
    hospitalAr: "مستشفى إن إم سي رويال دي آي بي، دبي",
    role: "doctor",
  },
  {
    staffId: "DOC1024",
    name: "Dr. Abdulla AlAmoodi",
    nameAr: "د. عبدالله العمودي",
    email: "queueless.staff+test1024@gmail.com",
    password: "Doctor123",
    department: "Family Medicine",
    departmentAr: "طب الأسرة",
    specialty: "Specialist Family Medicine",
    specialtyAr: "أخصائي طب الأسرة",
    languages: ["English", "Arabic"],
    hospital: "NMC Royal Hospital Khalifa City, Abu Dhabi",
    hospitalAr: "مستشفى إن إم سي رويال خليفة سيتي، أبوظبي",
    role: "doctor",
  },
  {
    staffId: "DOC1025",
    name: "Dr. Abduldayem Mando",
    nameAr: "د. عبد الدايم ماندو",
    email: "queueless.staff+test1025@gmail.com",
    password: "Doctor123",
    department: "Orthopaedics",
    departmentAr: "العظام",
    specialty: "Consultant Orthopaedic Surgeon",
    specialtyAr: "استشاري جراحة العظام",
    languages: ["English", "Arabic", "German"],
    hospital: "NMC Royal Hospital Sharjah",
    hospitalAr: "مستشفى إن إم سي رويال، الشارقة",
    role: "doctor",
  },
  {
    staffId: "DOC1026",
    name: "Dr. Ali Shakir",
    nameAr: "د. علي شاكر",
    email: "queueless.staff+test1026@gmail.com",
    password: "Doctor123",
    department: "Orthopaedics",
    departmentAr: "العظام",
    specialty: "Specialist Orthopaedics",
    specialtyAr: "أخصائي العظام",
    languages: ["English", "Arabic"],
    hospital: "NMC Specialty Hospital, Al Ain",
    hospitalAr: "مستشفى إن إم سي التخصصي، العين",
    role: "doctor",
  },
];

async function seedDoctors() {
  for (const doctor of doctors) {
    let userRecord;

    try {
      userRecord = await admin.auth().createUser({
        email: doctor.email,
        password: doctor.password,
        displayName: doctor.name,
      });

      console.log(`Auth created: ${doctor.name}`);
    } catch (error) {
      if (error.code === "auth/email-already-exists") {
        userRecord = await admin.auth().getUserByEmail(doctor.email);
        console.log(`Auth already exists: ${doctor.name}`);
      } else {
        throw error;
      }
    }
await db.collection("users").doc(userRecord.uid).set(
  {
    uid: userRecord.uid,
    staffId: doctor.staffId,

    // English + Arabic names
    name: doctor.name,
    nameAr: doctor.nameAr,

    email: doctor.email,

    // English + Arabic department
    department: doctor.department,
    departmentAr: doctor.departmentAr,

    // English + Arabic specialty
    specialty: doctor.specialty,
    specialtyAr: doctor.specialtyAr,

    languages: doctor.languages,

    // English + Arabic hospital
    hospital: doctor.hospital,
    hospitalAr: doctor.hospitalAr,

    role: doctor.role,
    status: "active",
    updatedAt: new Date(),
  },
  { merge: true }
);

    console.log(`Firestore updated: ${doctor.staffId} - ${doctor.name}`);
  }
}

seedDoctors().catch(console.error);